<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <None Update="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="PinguApps.BlazorSitemap" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    <ProjectReference Include="../Consumer/Consumer.csproj" />
  </ItemGroup>
</Project>
