using System;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.Build.Framework;
using Microsoft.Build.Utilities;

// Compiled by MSBuild's cross-platform Roslyn task factory; not part of the runtime assembly.
public sealed class BlazorSitemapSourceTask : Task
{
    [Required] public ITaskItem[] Sources { get; set; }
    [Required] public string ProjectDirectory { get; set; }
    [Required] public string OutputFile { get; set; }

    public override bool Execute()
    {
        try
        {
            StringBuilder generated = new StringBuilder("// <auto-generated/>\n");
            foreach (ITaskItem item in Sources.OrderBy(x => x.ItemSpec, StringComparer.Ordinal))
            {
                string path = item.GetMetadata("FullPath");
                string razor = ReadSource(path);
                // Track standard opt-in attributes, including fully qualified names and Attribute suffixes.
                if (!Regex.IsMatch(razor, @"^\s*@page\s+", RegexOptions.Multiline) ||
                    !Regex.IsMatch(razor, @"^\s*@attribute\s+.*\bSitemapPage(?:Attribute)?\b", RegexOptions.Multiline)) { continue; }
                string codeBehind = File.Exists(path + ".cs") ? "present\n" + ReadSource(path + ".cs") : "absent";
                string hash;
                using (SHA256 sha = SHA256.Create())
                {
                    hash = BitConverter.ToString(sha.ComputeHash(Encoding.UTF8.GetBytes(razor.Length.ToString(CultureInfo.InvariantCulture) + ":" + razor + codeBehind))).Replace("-", "").ToLowerInvariant();
                }
                string statePath = path + ".sitemap.json";
                string timestamp = null;
                if (File.Exists(statePath))
                {
                    string state = File.ReadAllText(statePath);
                    Match recorded = Regex.Match(state, "^\\s*\\{\\s*\"sha256\"\\s*:\\s*\"([a-f0-9]{64})\"\\s*,\\s*\"lastChangedUtc\"\\s*:\\s*\"([^\"]+)\"\\s*\\}\\s*$");
                    DateTimeOffset parsed;
                    if (!recorded.Success || !DateTimeOffset.TryParseExact(recorded.Groups[2].Value, "O", CultureInfo.InvariantCulture, DateTimeStyles.None, out parsed) || parsed.Offset != TimeSpan.Zero)
                    {
                        throw new InvalidOperationException("Invalid source freshness state: " + statePath + ". Restore it or delete it to intentionally reset the estimate.");
                    }
                    if (recorded.Groups[1].Value == hash) { timestamp = recorded.Groups[2].Value; }
                }
                if (timestamp == null)
                {
                    timestamp = DateTimeOffset.UtcNow.ToString("O", CultureInfo.InvariantCulture);
                    string state = "{\n  \"sha256\": \"" + hash + "\",\n  \"lastChangedUtc\": \"" + timestamp + "\"\n}\n";
                    WriteIfChanged(statePath, state);
                }
                string relative = Uri.UnescapeDataString(new Uri(Path.GetFullPath(ProjectDirectory) + Path.DirectorySeparatorChar).MakeRelativeUri(new Uri(path)).ToString());
                while (relative.StartsWith("../", StringComparison.Ordinal)) { relative = relative.Substring(3); }
                generated.Append("[assembly: global::System.Reflection.AssemblyMetadata(\"BlazorSitemap.Source/")
                    .Append(relative.Replace("\\", "\\\\").Replace("\"", "\\\""))
                    .Append("\", \"").Append(timestamp).Append("\")]\n");
            }
            WriteIfChanged(OutputFile, generated.ToString());
            return true;
        }
        catch (Exception exception)
        {
            Log.LogErrorFromException(exception, true);
            return false;
        }
    }

    private static string ReadSource(string path) => File.ReadAllText(path).Replace("\r\n", "\n").Replace("\r", "\n");

    private static void WriteIfChanged(string path, string content)
    {
        if (File.Exists(path) && File.ReadAllText(path) == content) { return; }
        Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(path)));
        File.WriteAllText(path, content, new UTF8Encoding(false));
    }
}
